# Copyright (C) 2018 Xiaomi

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := MiuiCalculator
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := MiuiCalculator/MiuiCalculator.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_OVERRIDES_PACKAGES := Calculator2 Calculator 
include $(BUILD_PREBUILT)
